export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "",
  brevoApiKey: process.env.BREVO_API_KEY ?? "",
  // InTouch API credentials
  INTOUCH_BASE_URL: process.env.INTOUCH_BASE_URL ?? "https://apidist.gutouch.net",
  INTOUCH_PARTNER_ID: process.env.INTOUCH_PARTNER_ID ?? "",
  INTOUCH_LOGIN_API: process.env.INTOUCH_LOGIN_API ?? "",
  INTOUCH_PASSWORD_API: process.env.INTOUCH_PASSWORD_API ?? "",
  INTOUCH_USERNAME: process.env.INTOUCH_USERNAME ?? "",
  INTOUCH_PASSWORD: process.env.INTOUCH_PASSWORD ?? "",
  INTOUCH_SERVICE_CODE: process.env.INTOUCH_SERVICE_CODE ?? "PAIEMENTMARCHANDOMPAYCIDIRECT",
};
